name: Open-irs

on:
  issues:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: stable
          run: node -v

      - name: Install dependencies
        run: npm ci
        
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Probot App
      - run: echo "Running"
      - run: npm start
