name: open-irs

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start OpenIRS server'

jobs:
  run-open-irs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up .env file
        run: cp .env.example .env  # Copy .env.example to .env, adjust if needed

      - name: Start OpenIRS server
        run: |
          while true; do
            npm start
            sleep 60  # wait a minute until restarting.
          done
